name: tests
on: [push]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v1

      - name: Set up PHP
        uses: shivammathur/setup-php@2.7.0
        with:
          php-version: '7.4'
          tools: 'composer:2.0.2'

      - name: Prepare project for development
        run: composer install

      - name: Run tests
        run: ./vendor/bin/phpunit tests

